SUBDIRS_x86				=    charfont libtools makeboot
SUBDIRS_stm32				=    charfont libtools
OBJECTS				=
TARGETS				=
CONFIGS				=
RULE_SUFFIX			=	$(HOST_RULE)
OBJECTS_PATH		=	$(OBJECTS_TOOL)
CONFIGS_PATH		=
TARGETS_PATH		=	$(TARGETS_TOOL)
DEPENDS_PATH		=	$(DEPENDS_TOOL)