SUBDIRS				=	$(FWLIB)
CONFIGS				=
TARGETS				=	$(TARGETS_PATH)/$(CURRENT_FOLDER)$(STATIC_LIBRARY)
#OBJECTS_PATH		=	$(OBJECTS_ROOT)/$(CURRENT_FOLDER)
CONFIGS_PATH		=
#TARGETS_PATH		=	$(TARGETS_ROOT)
